/*
 * Generated by Digital. Don't modify this file!
 * Any changes will be lost if this file is regenerated.
 */

module full_adder (
  input a,
  input b,
  input cin,
  output sum,
  output cout
);
  assign sum = (a ^ b ^ cin);
  assign cout = ((b & cin) | (cin & a) | (b & a));
endmodule

module four_bit_adder (
  input [3:0] a,
  input [3:0] b,
  input cin,
  output [3:0] y,
  output overfl,
  output cout
);
  wire s0;
  wire s1;
  wire s2;
  wire s3;
  wire s4;
  wire s5;
  wire s6;
  wire s7;
  wire s8;
  wire s9;
  wire s10;
  wire s11;
  wire s12;
  wire s13;
  wire s14;
  wire cout_temp;
  assign s0 = a[0];
  assign s1 = a[1];
  assign s2 = a[2];
  assign s3 = a[3];
  assign s4 = b[0];
  assign s5 = b[1];
  assign s6 = b[2];
  assign s7 = b[3];
  full_adder full_adder_i0 (
    .a( s0 ),
    .b( s4 ),
    .cin( cin ),
    .sum( s8 ),
    .cout( s9 )
  );
  full_adder full_adder_i1 (
    .a( s1 ),
    .b( s5 ),
    .cin( s9 ),
    .sum( s10 ),
    .cout( s11 )
  );
  full_adder full_adder_i2 (
    .a( s2 ),
    .b( s6 ),
    .cin( s11 ),
    .sum( s12 ),
    .cout( s13 )
  );
  full_adder full_adder_i3 (
    .a( s3 ),
    .b( s7 ),
    .cin( s13 ),
    .sum( s14 ),
    .cout( cout_temp )
  );
  assign y[0] = s8;
  assign y[1] = s10;
  assign y[2] = s12;
  assign y[3] = s14;
  assign overfl = (s13 ^ cout_temp);
  assign cout = cout_temp;
endmodule
